// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kjgfogrhpducqnwjmlvp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtqZ2ZvZ3JocGR1Y3Fud2ptbHZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg1MjY5NzgsImV4cCI6MjA1NDEwMjk3OH0.tgF_xIKkiqBP6q5TBnbE9OoIT4pElS9_SA7y83gWhl0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);